

spring:
  datasource:
    url: jdbc:mysql://124.222.61.69:3306/hello?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Azurlane416!
    # redis ??
  redis:
    # ??
    host: 124.222.61.69
    # ??????6379
    port: 6379
    # ?????
    database: 0
    # ??
    password: Azurlane416!
    # ??????
    timeout: 10s
server:
  port: 8233

